using System.Linq;
using Sonolume.Engine.Input;
using Sonolume.Engine.Model;

namespace Sonolume.Engine.Mappings;

/// <summary>The fixed note-per-param convention every zone/group is wired with. Each zone/group claims a whole
/// MIDI octave (12 consecutive notes, see <see cref="AllocateOctave"/>) - always the same offsets within it drive
/// the same params, so the same effect param on two different zones always lands on the same note, just in a
/// different octave. Once every octave on a channel is claimed, allocation spills onto the next channel. The
/// octave's root ("C") is reserved for the target's Trigger/Gate "Key" mapping (see SonolumeSession.AddZone/
/// AddGroup and <see cref="KeySourceOf"/>) - unlike the rest of the octave, that one mapping isn't generated by
/// <see cref="For"/> and stays user-learnable; this just gives a freshly created one somewhere sensible to start.
/// Beyond that, nothing in the UI can repoint a param to a different note; the editor just labels each row with
/// its note (see SonolumeView.BuildMacroLabel).</summary>
public static class DefaultMacros
{
    private const int NotesPerOctave = 12;
    private const int OctavesPerChannel = 128 / NotesPerOctave;
    private const int ChannelCount = 16;

    /// <summary>Offset within the octave reserved for the target's Trigger/Gate "Key" mapping - the octave's root
    /// ("C"), one note below the Type row. Not generated by <see cref="For"/> itself (see <see cref="KeySourceOf"/>).</summary>
    private const int KeyOffset = 0;

    /// <summary>Offset within the octave dedicated to effect-type switching (a Select-mode mapping, see
    /// <see cref="MappingMode.Select"/>) - the "Type" row's note.</summary>
    private const int EffectTypeOffset = 1;

    /// <summary>Offset dedicated to blend switching (a Select-mode mapping tagged <see cref="ParamId.Blend"/>) -
    /// the "Blend" row's note. Zones only: groups have no blend mode of their own, so their octave leaves this
    /// note unused.</summary>
    private const int BlendOffset = 2;

    private const int ParamsStartOffset = 3;

    /// <summary>The continuous Set-mode params, in the same top-to-bottom order as the color/modulation/position
    /// rows below the Type and Blend rows. EffectRotation is appended rather than inserted near PosX/PosY so every
    /// param note offset already handed out for an existing project stays put (see <see cref="AllocateOctave"/>).</summary>
    private static readonly ParamId[] Params =
    {
        ParamId.Hue,
        ParamId.Saturation,
        ParamId.Brightness,
        ParamId.EffectIntensity,
        ParamId.EffectSpeed,
        ParamId.EffectDecay,
        ParamId.PosX,
        ParamId.PosY,
        ParamId.EffectRotation,
    };

    /// <summary>The note (and channel) that already drives <paramref name="target"/>'s Set-mode mapping for
    /// <paramref name="param"/> - reads back whatever octave <see cref="For"/> assigned it, never re-allocates.
    /// Null only if <paramref name="target"/> hasn't been synced yet (see <see cref="Sync"/>).</summary>
    public static SourceAddress? ParamSourceOf(Project project, TargetRef target, ParamId param) =>
        project.Mappings.FirstOrDefault(m => m.Target == target && m.Mode == MappingMode.Set && m.Param == param)?.Source;

    /// <summary>The root note ("C") of <paramref name="target"/>'s octave - one note below the effect-type Select
    /// mapping's note - reserved for its Trigger/Gate "Key" mapping. Unlike <see cref="EffectTypeSourceOf"/> and
    /// friends this isn't reading back an existing Select/Set mapping (the Key isn't one of those; it stays a
    /// normal, user-learnable mapping), just deriving where in the octave it belongs. Null until the target has
    /// been synced (see <see cref="Sync"/>).</summary>
    public static SourceAddress? KeySourceOf(Project project, TargetRef target)
    {
        if (EffectTypeSourceOf(project, target) is not { } effectType) return null;
        return new SourceAddress(SourceKind.MidiNote, effectType.Channel, effectType.Number - (EffectTypeOffset - KeyOffset));
    }

    /// <summary>The note (and channel) that drives <paramref name="target"/>'s effect-type Select mapping.</summary>
    public static SourceAddress? EffectTypeSourceOf(Project project, TargetRef target) =>
        project.Mappings.FirstOrDefault(m => m.Target == target && m.Mode == MappingMode.Select && m.Param != ParamId.Blend)?.Source;

    /// <summary>The note (and channel) that drives <paramref name="target"/>'s blend Select mapping. Zones only.</summary>
    public static SourceAddress? BlendSourceOf(Project project, TargetRef target) =>
        project.Mappings.FirstOrDefault(m => m.Target == target && m.Mode == MappingMode.Select && m.Param == ParamId.Blend)?.Source;

    /// <summary>Builds <paramref name="target"/>'s fixed note-per-param mapping set, first finding it a free octave
    /// (see <see cref="AllocateOctave"/>) from <paramref name="project"/>'s current mappings. Callers must add the
    /// result to <paramref name="project"/> (directly, or via an <see cref="Engine.Engine"/> wrapping it) before
    /// allocating for the next target, so the octave just claimed stays visible to the scan.</summary>
    public static List<Mapping> For(Project project, TargetRef target)
    {
        var (channel, baseNote) = AllocateOctave(project.Mappings, target);
        var mappings = new List<Mapping>();

        mappings.Add(new Mapping
        {
            Id = $"macro:type:{target.Kind}:{target.Id}",
            Source = SourceAddress.Note(baseNote + EffectTypeOffset, channel),
            Target = target,
            Param = ParamId.EffectIntensity, // just a tag; ignored for Select mode
            Mode = MappingMode.Select,
            Transform = Transform.Identity,
        });

        // Groups have no blend mode of their own - only a zone's Blend row gets this note.
        if (target.Kind == TargetKind.Zone)
        {
            mappings.Add(new Mapping
            {
                Id = $"macro:blend:{target.Kind}:{target.Id}",
                Source = SourceAddress.Note(baseNote + BlendOffset, channel),
                Target = target,
                Param = ParamId.Blend,
                Mode = MappingMode.Select,
                Transform = Transform.Identity,
            });
        }

        for (int i = 0; i < Params.Length; i++)
        {
            mappings.Add(new Mapping
            {
                Id = $"macro:param:{Params[i]}:{target.Kind}:{target.Id}",
                Source = SourceAddress.Note(baseNote + ParamsStartOffset + i, channel),
                Target = target,
                Param = Params[i],
                Mode = MappingMode.Set,
                Transform = Transform.Identity,
            });
        }

        return mappings;
    }

    /// <summary>Finds the first (channel, octave) pair - scanning channel 0 upward, then octave 0 upward within
    /// each channel - whose whole 12-note block is free of any existing MIDI-note mapping belonging to some other
    /// target: another target's octave, or another zone/group's "Key" trigger note (see
    /// SonolumeSession.AddZone/AddGroup). <paramref name="target"/>'s own existing notes never block its own
    /// reallocation - without that exclusion, a target's Key mapping (which sits at the octave's root once placed,
    /// see <see cref="KeySourceOf"/>, but isn't itself regenerated by <see cref="Sync"/>) would look like an
    /// occupied block on every re-Sync and knock that target onto a fresh octave every time, drifting its params
    /// away from its own Key. A Key note's default any-channel wildcard reserves its number on every channel, so
    /// it blocks a candidate octave regardless of which channel is being tried; a note pinned to one channel (every
    /// octave this method hands out is) only blocks that channel.</summary>
    private static (int Channel, int BaseNote) AllocateOctave(IReadOnlyList<Mapping> mappings, TargetRef target)
    {
        for (int channel = 0; channel < ChannelCount; channel++)
        {
            for (int octave = 0; octave < OctavesPerChannel; octave++)
            {
                int baseNote = octave * NotesPerOctave;
                if (IsFree(mappings, target, channel, baseNote)) return (channel, baseNote);
            }
        }

        // Exhausted 160 octaves (16 channels x 10) - astronomically more than any real rig needs. Degrade to
        // overlapping notes on the last slot rather than throw.
        return (ChannelCount - 1, (OctavesPerChannel - 1) * NotesPerOctave);
    }

    private static bool IsFree(IReadOnlyList<Mapping> mappings, TargetRef target, int channel, int baseNote)
    {
        foreach (var m in mappings)
        {
            if (m.Target == target) continue;
            if (m.Source.Kind != SourceKind.MidiNote) continue;
            if (m.Source.Channel != SourceAddress.Any && m.Source.Channel != channel) continue;
            int note = m.Source.Number;
            if (note >= baseNote && note < baseNote + NotesPerOctave) return false;
        }
        return true;
    }

    /// <summary>Re-derives every macro-convention mapping from the fixed convention, for every zone and group, in
    /// that order (so octave allocation stays stable run to run as long as the zone/group list itself doesn't
    /// change). Called on every project load.</summary>
    public static void Sync(Project project)
    {
        project.Mappings.RemoveAll(m => m.Id.StartsWith("macro:", StringComparison.Ordinal));
        foreach (var zone in project.Zones) project.Mappings.AddRange(For(project, TargetRef.Zone(zone.Id)));
        foreach (var group in project.Groups) project.Mappings.AddRange(For(project, TargetRef.Group(group.Id)));
    }
}
